### ISSUE TITLE
can I create documentation in readme for this project it looks Exciting.

### ISSUE THREAD

**Issue by piyush-mahajan** [mack64948/PeriodicTable#1]

**Comment by mack64948** [comment]
Hi Piyush, thank you for your message.  I really appreciate your offer to help and thank you for your interest in the project.  The project as of now is a clone of an existing project, namely ptable.com, that I am trying to reverse engineer and use for demonstration and teaching purposes.  I hope to  use it as a starting point for other projects and will eventually add unique content.  If you're still interested, let me know.

**Comment by piyush-mahajan** [comment]
sounds exciting, can you assign it to me?

**Comment by mack64948** [comment]
Okay cool.  I appreciate your interest.  Based on your portfolio page, you
are a very talented front-end dev.  However, I'm still not finished coding
all the functionality.  Are you able to figure it out based on how it works
so far? How do you plan to write the documentation? In markdown? Thanks

**Comment by piyush-mahajan** [comment]
thanks for your appreciation 🙂, yes I figured out how it will work so far and would love to work with you o this project; documentation will take time as the project grows.
